language: node_js
node_js:
  - node
addons:
  firefox: latest
install:
  - npm install -g selenium-webdriver
  - npm install -g npm@6.14.11
  - npm install --global web-ext
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz -P ~/
  - tar -xzf ~/geckodriver-v0.29.0-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.29.0-linux64.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
